name: ff

dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
  - python=3.6.2

  - pip:
    - azureml-sdk[automl]
    - azureml-defaults
    - azureml-widgets
    - inference-schema
    - joblib==0.14.1
    # - pyarrow==0.14
    - pyarrow<2.0.0,>=0.17.0
    - azureml-dataprep<2.1.0a,>=2.0.1a
    - py-cpuinfo==5.0.0
    - azure-storage-blob==12.3.0
    - opencensus-ext-azure>=1.0.1
  - numpy==1.16.2
  - pandas==0.23.4
  - scikit-learn>=0.19.0,<=0.20.3
  - py-xgboost==0.90
  - fbprophet==0.5
  - psutil>=5.2.2,<6.0.0
channels:
  - anaconda
  - conda-forge