name: BSF build pipeline

resources:
  containers:
  #- container: mlops
  #  image: mcr.microsoft.com/mlops/python:latest
  - container: mlops
    image: garywamlcr.azurecr.io/public/mlops/python:latest
    endpoint: acrconnection

pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ml_service/pipelines/ff_create_scoring_image.py

variables:
- template: ff-variables.yml
- group: mmmo-vg

# pool: MachineLearningAgent
pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Deploy_Webapp'
  displayName: 'Deploy to Webapp'
  condition: and(succeeded(), variables['WEBAPP_DEPLOYMENT_NAME'])
  jobs:
  - job: "Deploy_Webapp"
    displayName: "Deploy to Webapp"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - task: AzureCLI@1
      displayName: 'Create scoring image and set IMAGE_LOCATION variable'
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          python -m ml_service.util.ff_create_scoring_image --output_image_location_file image_location.txt
          # Output image location to Azure DevOps job
          IMAGE_LOCATION="$(cat image_location.txt)"
          echo "##vso[task.setvariable variable=IMAGE_LOCATION]$IMAGE_LOCATION"
    - bash: echo $(IMAGE_LOCATION)
    - task: AzureCLI@2
      name: CreateWebApp
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az appservice plan create --name '$(WEBAPP_DEPLOYMENT_NAME)plan' --resource-group '$(RESOURCE_GROUP)' --location '$(LOCATION)' --is-linux --sku F1
          az webapp create --name '$(WEBAPP_DEPLOYMENT_NAME)' --plan '$(WEBAPP_DEPLOYMENT_NAME)plan' --resource-group '$(RESOURCE_GROUP)' --deployment-container-image-name '$(IMAGE_LOCATION)'
    - task: AzureWebAppContainer@1
      name: WebAppDeploy
      displayName: 'Azure Web App on Container Deploy'
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        appName: '$(WEBAPP_DEPLOYMENT_NAME)'
        resourceGroupName: '$(RESOURCE_GROUP)'
        containers: '$(IMAGE_LOCATION)'
    - task: AzureCLI@1
      displayName: 'Smoke test'
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          python -m ml_service.util.ff_smoke_test_scoring_service --type Webapp --service "$(WebAppDeploy.AppServiceApplicationUrl)/score"
